import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#0053db",
        "surface-variant": "#dae2fd",
        "on-primary-fixed": "#00174b",
        "on-tertiary-fixed": "#23005c",
        "secondary-fixed-dim": "#4cd7f6",
        "inverse-surface": "#283044",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#004e5c",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#e9ddff",
        "inverse-primary": "#b4c5ff",
        "inverse-on-surface": "#eef0ff",
        "on-primary-container": "#eeefff",
        "surface-dim": "#d2d9f4",
        "primary-fixed": "#dbe1ff",
        "on-error-container": "#93000a",
        secondary: "#00687a",
        "error-container": "#ffdad6",
        outline: "#737686",
        "primary-fixed-dim": "#b4c5ff",
        "on-background": "#131b2e",
        "on-secondary-fixed": "#001f26",
        "on-surface-variant": "#434655",
        "tertiary-fixed-dim": "#d0bcff",
        "secondary-fixed": "#acedff",
        "surface-container-high": "#e2e7ff",
        "on-tertiary-container": "#f6edff",
        surface: "#faf8ff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-bright": "#faf8ff",
        primary: "#004ac6",
        "on-secondary-container": "#006172",
        "outline-variant": "#c3c6d7",
        "tertiary-container": "#7d4ce7",
        "surface-container": "#eaedff",
        tertiary: "#632ecd",
        "on-surface": "#131b2e",
        "surface-container-highest": "#dae2fd",
        "on-tertiary-fixed-variant": "#5516be",
        "on-primary-fixed-variant": "#003ea8",
        error: "#ba1a1a",
        "secondary-container": "#57dffe",
        "surface-container-low": "#f2f3ff",
        background: "#faf8ff",
        "primary-container": "#2563eb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        gutter: "1.25rem",
        "gutter-lg": "1.5rem",
        margin: "1.5rem",
        "margin-lg": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "code-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-lg": ["Inter"],
        "display-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "code-sm": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.625rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["1.625rem", { lineHeight: "2.125rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["0.75rem", { lineHeight: "1.125rem", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-md": ["1.375rem", { lineHeight: "1.875rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg": ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.03em", fontWeight: "700" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.03em", fontWeight: "500" }],
        "body-md": ["0.875rem", { lineHeight: "1.375rem", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
